version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - AESGCM
  - agentic
  - ainvoke
  - ALIP
  - anonymization
  - asyncio
  - charliermarsh
  - checkpointing
  - commitizen
  - conftest
  - contextvars
  - dataclass
  - dataclasses
  - debugpy
  - Decendent
  - demoability
  - Docling
  - dotenv
  - dspy
  - evals
  - fastapi
  - fintech
  - genai
  - Genalog
  - HITL
  - htmlcov
  - httpx
  - inmem
  - inspectable
  - jailbreaking
  - Langchain
  - langgraph
  - Langsmith
  - MEAP
  - memgraph
  - mypy
  - NAIC
  - negotiables
  - OIPA
  - Ollama
  - pkill
  - pseudonymized
  - pycache
  - Pydantic
  - PYDEVD
  - pyproject
  - pytest
  - PYTHONDONTWRITEBYTECODE
  - Pythonic
  - pythonpath
  - PYTHONUNBUFFERED
  - pyyaml
  - Recompiles
  - rollups
  - Streamlit
  - structlog
  - Synthea
  - tamasfe
  - Tiltfile
  - Touchpoint
  - typecheckers
  - typer
  - uvicorn
  - Vaultless
  - venv
  - workshopping
  - Xfrozen
  - yzhang
ignoreWords: []
import: []
