from typing import Any, Protocol


class LoggerProtocol(Protocol):
    """
    Abstract logger interface for use cases so they can emit structured telemetry
    without coupling to an external concrete framework like structlog.
    """

    def bind(self, **kwargs: Any) -> "LoggerProtocol": ...

    def unbind(self, *keys: str) -> "LoggerProtocol": ...

    def debug(self, event: str, **kwargs: Any) -> None: ...

    def info(self, event: str, **kwargs: Any) -> None: ...

    def warning(self, event: str, **kwargs: Any) -> None: ...

    def error(self, event: str, **kwargs: Any) -> None: ...

    def exception(self, event: str, exc_info: Exception | bool = True, **kwargs: Any) -> None: ...
